name: cocktail_app
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.2
  meta: any

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
  build_runner: ^1.10.1
  json_serializable: ^3.4.1